N lexers
wakatime/chroma pull request #103
Opened 2021-01-22 17:54 UTC by gandarez

This PR adds missing `n` package lexers.

- Ncl
- NSIS
- Nasm Objdump
- nesC
- Nimrod
- Nit
- Notmuch
- NuSMV
- NumPy

Closes https://github.com/wakatime/wakatime-cli/issues/213

2021-01-22 23:42 UTC, dron22 requested changes

2021-01-22 23:42 UTC, dron22 commented on lexers/n/nsis.go
> +		Aliases:   []string{"nsis", "nsis", "nsh"},
small typo here:
```suggestion
		Aliases:   []string{"nsis", "nsi", "nsh"},
```

2021-01-22 23:42 UTC, dron22 commented on lexers/n/numpy.go
> +	matched, _ := shebang.MatchString(text, `pythonw?(3(\.\d)?)?`)
yeah, this if condition is very long. I like the approach with `matched` variable. Maybe we can even extend it, to fully remove this long line.
```suggestion
	hasPythonShebang, _ := shebang.MatchString(text, `pythonw?(3(\.\d)?)?`)
	...

	if (hasPythonShebang || containsImport) && (hasNumpyImport || hasFromNumpyImport) {
	    return 1.0
	}
```

2021-01-22 23:42 UTC, dron22 commented on lexers/n/numpy_test.go
> +	data, err := ioutil.ReadFile("testdata/numpy")
As the text analysis has a more complicated if condition, can we add additional test cases?

2021-01-26 12:01 UTC, gandarez commented
@dron22 fixes applied and test cases added for NumPy.

2021-01-26 21:16 UTC, dron22 approved these changes
Alright great. Just one small typo in test function name left. Approving already :+1:

2021-01-26 21:16 UTC, dron22 commented on lexers/n/notmuch_test.go
> +func TestNtmuch_AnalyseText(t *testing.T) {
small typo
```suggestion
func TestNotmuch_AnalyseText(t *testing.T) {
```

2021-01-27 16:25 UTC, merged