Add set text analyser for MySQL lexer
wakatime/chroma pull request #17
Opened 2020-11-08 18:57 UTC by gandarez

This PR ports pygments MySQL text analysis to chroma/go. Original code can be found at: https://github.com/pygments/pygments/blob/master/pygments/lexers/sql.py#L752

The current pygments analysis seems to be wrong according to some reasearch on the documentation and local testing. There's no way to use square brackets to compound MySQL queries. As it's a veredict I removed all the logic comparison between square brackets and backticks. Here's the [PR](https://github.com/pygments/pygments/pull/1593) opened for pygments.

https://stackoverflow.com/a/9719904/833531
https://dev.mysql.com/doc/refman/8.0/en/identifiers.html

Fixes: wakatime/wakatime-cli#91

2020-11-08 21:13 UTC, dron22 reviewed
Alright, good catch. What I am not sure is the value you are returning. If we look at the first if statement:
```python
if dialect_name_count >= 1 and \
           name_between_backtick_count >= 2 * name_between_bracket_count:
            # Found at least twice as many `name` as [name].
            rating += 0.5
        elif name_between_backtick_count > name_between_bracket_count:
            rating += 0.2
        elif name_between_backtick_count > 0:
            rating += 0.1
```
.. and we consider that there will > 1 name between backticks and there won't be any square brackets. The first if statement will still evaluate to true and it will return `0.5`.

2020-11-12 22:04 UTC, dron22 commented
What I wanted to say here is, that we have to return `0.5` to have the same behavior like the pygments implementation.

2020-11-29 06:09 UTC, dron22 requested changes
I checked it again. We should return `0.2`. Because if we have a name between backticks, the second if condition will resolve to `True` in pygments version. `name_between_backtick_count` will be greater than `name_between_bracket_count`:
```
elif name_between_backtick_count > name_between_bracket_count:
```
Regarding the first if condition, I was wrong in my first PR remark. It will never resolve to `True`, as it includes this multiplication with `name_between_bracket_count`, which will always be `0`:
```
dialect_name_count >= 1 and name_between_backtick_count >= 2 * name_between_bracket_count
```

2020-11-29 06:09 UTC, dron22 commented on lexers/m/mysql.go
> +		return 0.1
This is what I mean.
```suggestion
		return 0.2
```

2020-12-14 17:38 UTC, gandarez commented
@dron22 I reverted back to the original porting from Pygments. Could you please review it?

2020-12-14 22:09 UTC, dron22 approved these changes

2020-12-15 00:11 UTC, merged