J lexers
wakatime/chroma pull request #97
Opened 2021-01-19 13:08 UTC by gandarez

This PR adds missing `j` package lexers.

- JCL [ref](https://github.com/pygments/pygments/blob/a590ac5ea7c00a41e253834306bfa19e38349c0b/pygments%2Flexers%2Fscripting.py#L1149)
- JSGF [ref](https://github.com/pygments/pygments/blob/a590ac5ea7c00a41e253834306bfa19e38349c0b/pygments%2Flexers%2Fgrammar_notation.py#L136)
- JSONBareObject is deprecated in pygments and has not been ported to Chroma.
- JSON-LD [ref](https://github.com/pygments/pygments/blob/a590ac5ea7c00a41e253834306bfa19e38349c0b/pygments%2Flexers%2Fdata.py#L652)
- Java Server Page [ref](https://github.com/pygments/pygments/blob/a590ac5ea7c00a41e253834306bfa19e38349c0b/pygments%2Flexers%2Ftemplates.py#L1357). Strangely it calls text analysis from Java which is not implemented yet. Anyway I ported exactly as it is in Pygments.
- Julia Console [ref](https://github.com/pygments/pygments/blob/a590ac5ea7c00a41e253834306bfa19e38349c0b/pygments%2Flexers%2Fjulia.py#L284)
- Juttle [ref](https://github.com/pygments/pygments/blob/a590ac5ea7c00a41e253834306bfa19e38349c0b/pygments%2Flexers%2Fjavascript.py#L1471)

Closes https://github.com/wakatime/wakatime-cli/issues/209

2021-01-19 21:23 UTC, dron22 requested changes

2021-01-19 21:23 UTC, dron22 commented on lexers/j/jsgf.go
> +		Filenames: []string{"*.Jsgf"},
typo: should be lower case
```suggestion
		Filenames: []string{"*.jsgf"},
```

2021-01-19 21:54 UTC, gandarez commented on lexers/j/jsgf.go
> +		Filenames: []string{"*.Jsgf"},
tks.

2021-01-20 20:14 UTC, dron22 approved these changes

2021-01-21 17:55 UTC, merged